import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { kitRoot } from "../render.js";
import { parseAgent } from "../agent-frontmatter.js";
import { MCP_SERVERS } from "../mcp.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const PLUGIN = `// Generated by research-copilot. Per-turn context injection for OpenCode.
// Spawns the \`rc\` CLI as a subprocess (single injection codepath; no in-process core import).
import { execFileSync } from "node:child_process";

export const ResearchCopilot = async () => ({
  "experimental.chat.system.transform": async (_input: unknown, output: { system: string[] }) => {
    try {
      const block = execFileSync("rc", ["context", "--platform", "opencode", "--format", "text"], {
        cwd: process.cwd(), encoding: "utf8", timeout: 20000,
      });
      if (block && block.trim()) output.system.push(block);
    } catch {
      // rc not on PATH or no .research/ yet — skip injection this turn
    }
  },
});
`;

export function configureOpenCode(repo: string): void {
  const base = path.join(repo, ".opencode");
  fs.mkdirSync(path.join(base, "agent"), { recursive: true });
  fs.mkdirSync(path.join(base, "plugin"), { recursive: true });
  const KIT = kitRoot(__dirname);

  const agentsSrc = path.join(KIT, "agents");
  for (const f of fs.readdirSync(agentsSrc).filter(x => x.endsWith(".md"))) {
    const a = parseAgent(fs.readFileSync(path.join(agentsSrc, f), "utf8"));
    const fm = ["---", `description: ${JSON.stringify(a.description)}`, "mode: subagent"];
    if (a.model) fm.push(`model: ${a.model}`);
    fm.push("---", "");
    fs.writeFileSync(path.join(base, "agent", a.name + ".md"), fm.join("\n") + a.body + "\n", "utf8");
  }

  fs.writeFileSync(path.join(base, "plugin", "research-copilot.ts"), PLUGIN, "utf8");

  // opencode.json — register MCP servers in OpenCode local shape (command is an array).
  // Merge-safe (preserve foreign mcp entries) + idempotent (overwrite only our keys).
  const ocPath = path.join(repo, "opencode.json");
  const oc = fs.existsSync(ocPath) ? JSON.parse(fs.readFileSync(ocPath, "utf8")) : {};
  oc.mcp = { ...(oc.mcp ?? {}) };
  for (const [name, def] of Object.entries(MCP_SERVERS)) {
    oc.mcp[name] = { type: "local", command: [def.command, ...def.args] };
  }
  fs.writeFileSync(ocPath, JSON.stringify(oc, null, 2) + "\n", "utf8");
}
