import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { kitRoot } from "../render.js";
import { parseAgent } from "../agent-frontmatter.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const PLUGIN = `// Generated by research-copilot. Per-turn context injection for OpenCode.
// Spawns the \`rc\` CLI as a subprocess (single injection codepath; no in-process core import).
import { execFileSync } from "node:child_process";

export const ResearchCopilot = async () => ({
  "experimental.chat.system.transform": async (_input: unknown, output: { system: string[] }) => {
    try {
      const block = execFileSync("rc", ["context", "--platform", "opencode", "--format", "text"], {
        cwd: process.cwd(), encoding: "utf8", timeout: 20000,
      });
      if (block && block.trim()) output.system.push(block);
    } catch {
      // rc not on PATH or no .research/ yet — skip injection this turn
    }
  },
});
`;

export function configureOpenCode(repo: string): void {
  const base = path.join(repo, ".opencode");
  fs.mkdirSync(path.join(base, "agent"), { recursive: true });
  fs.mkdirSync(path.join(base, "plugin"), { recursive: true });
  const KIT = kitRoot(__dirname);

  const agentsSrc = path.join(KIT, "agents");
  for (const f of fs.readdirSync(agentsSrc).filter(x => x.endsWith(".md"))) {
    const a = parseAgent(fs.readFileSync(path.join(agentsSrc, f), "utf8"));
    const fm = ["---", `description: ${JSON.stringify(a.description)}`, "mode: subagent"];
    if (a.model) fm.push(`model: ${a.model}`);
    fm.push("---", "");
    fs.writeFileSync(path.join(base, "agent", a.name + ".md"), fm.join("\n") + a.body + "\n", "utf8");
  }

  fs.writeFileSync(path.join(base, "plugin", "research-copilot.ts"), PLUGIN, "utf8");
}
